apiVersion: v1
kind: Pod
metadata:
  labels:
    run: worker-pod
  name: worker-pod
spec:
  terminationGracePeriodSeconds: 60
  containers:
    - image: alpine
      name: alpine
      command:
        - "sleep"
        - "99999999"
      lifecycle:
        preStop:
          exec:
            command:
              - sh
              - -c
              - curl 10.244.1.10
