apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  name: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
        - image: nginx
          name: nginx
          env:
            - name: VIRTUAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-demo
                  key: virtual_host
          volumeMounts:
            - name: index-html
              mountPath: "/usr/share/nginx/app1/index.html"
              subPath: "index.html"
            - name: vhost
              mountPath: "/etc/nginx/conf.d/vhost.conf"
              subPath: "vhost.conf"
      volumes:
        - name: index-html
          configMap:
            name: nginx-demo
            items:
              - key: "index.html"
                path: "index.html"
        - name: vhost
          configMap:
            name: nginx-demo
            items:
              - key: "vhost.conf"
                path: "vhost.conf"
